### ISSUE TITLE
[FEAT 👩‍💻] Main -> Sub Activity 전환

### ISSUE THREAD

**Issue by JaeHyeonSim** [kotlin-project-team/frontend#1]
## Description ✏️
- Main Activity에서 Sub Activity로 전환하는 기능을 구현합니다.
## Todo
- [x] Main - Notice 연결
- [x] Main - Best 연결
- [x] Main - Normal 연결
