### ISSUE TITLE
[REF 👩‍💻] 코드 리팩토링

### ISSUE THREAD

**Issue by JaeHyeonSim** [kotlin-project-team/frontend#14]
## Description ✏️
전반적인 코드 리팩토링을 진행합니다.
## Todo
- [x] nullable 선언 최소화
- [x] 불필요한 코드 삭제
- [x] rename, data type 변경, 자잘한 설정값 변경 등
