### ISSUE TITLE
[DESIGN 💄] Design Style 변경 2

### ISSUE THREAD

**Issue by JaeHyeonSim** [kotlin-project-team/frontend#23]
## Description ✏️
UI 디자인 수정 2차입니다.
## Todo
- [x] background 색상 변경
- [ ] button design source 추가
- [x] activity 이동 -> fragment로 변경
