### ISSUE TITLE
[REF 👩‍💻] Type 정리

### ISSUE THREAD

**Issue by JaeHyeonSim** [kotlin-project-team/frontend#32]
## Description ✏️
Response type, Response status type, board category type을 정리합니다. 백엔드 코드를 참고하였습니다.
## Todo
- [x] Wrapper class APIResponse 정의
- [x] String -> Enum type : BoardCategoryType 추가
- [x] String -> Enum type : ResponseStatusType 추가
