### ISSUE TITLE
[REF 👩‍💻] 코드 리팩토링

### ISSUE THREAD

**Issue by JaeHyeonSim** [kotlin-project-team/frontend#40]
## Description ✏️
개발 초기에 사용했던 안드로이드 내부 Room DB는 API 연결 이후로 사용하지 않으므로 코드를 제거하고, Post, Notice 등 변경된 req & res data를 적용하여  전반적인 코드 리팩토링을 진행합니다.
## Todo
- [x] Room DB 사용 코드 제거
- [x] 불필요한 파일 및 코드 삭제
- [x] property public to private
- [x] data class 수정
- [x] data 수정 사항 반영
