### ISSUE TITLE
[FEAT 👩‍💻] Status code에 따른 response 처리

### ISSUE THREAD

**Issue by JaeHyeonSim** [kotlin-project-team/frontend#46]
## Description ✏️
status code에 따라 response를 처리하고, 오류를 다룹니다.
## Todo
- [x] post 관련 crud
- [x] notice 관련 crud
- [ ] user 관련 crud
- [ ] comment 관련 crud
